const products = [
    {
        id: 0,
        name: "prod1",
        price: 29.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 1,
        name: "prod2",
        price: 34.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 2,
        name: "prod3",
        price: 59.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 3,
        name: "prod4",
        price: 64.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 4,
        name: "prod5",
        price: 71.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 5,
        name: "prod6",
        price: 99.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 6,
        name: "prod7",
        price: 9.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 7,
        name: "prod8",
        price: 13.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 8,
        name: "prod9",
        price: 19.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 9,
        name: "prod10",
        price: 119.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 10,
        name: "prod11",
        price: 149.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 11,
        name: "prod12",
        price: 199.99,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
]