const products = [
    {
        id: 0,
        name: "Produkt 1",
        manufacterer: "Nike",
        price: 29.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 1,
        name: "Produkt 2",
        manufacterer: "Adidas",
        price: 34.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 2,
        name: "Produkt 3",
        manufacterer: "Vans",
        price: 59.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 3,
        name: "Produkt 4",
        manufacterer: "Nike",
        price: 64.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 4,
        name: "Produkt 5",
        manufacterer: "Vans",
        price: 71.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 5,
        name: "Produkt 6",
        manufacterer: "Vans",
        price: 99.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 6,
        name: "Produkt 7",
        manufacterer: "Adidas",
        price: 9.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 7,
        name: "Produkt 8",
        manufacterer: "Nike",
        price: 13.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 8,
        name: "Produkt 9",
        manufacterer: "Nike",
        price: 19.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 9,
        name: "Produkt 10",
        manufacterer: "Adidas",
        price: 119.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 10,
        name: "Produkt 11",
        manufacterer: "Adidas",
        price: 149.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
    {
        id: 11,
        name: "Produkt 12",
        manufacterer: "Vans",
        price: 199.99,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
        imgSrc: "https://picsum.photos/100",
    },
]